package pidgeon;

public class arrays {

    /*
     DUTCH DEPENDACIES
     */
    public static String DutchIrr[][] = {
        {"", "Can", "kunnen"},
        {"To", "have", "Hebben"},
        {"", "May", "Mogen"},
        {"To", "Want", "Willen"},
        {"To", "be", "Zijn"},
        {"", "Will", "Zullen"},
    };

    public static String Dutch[][] = {
        {"To", "drink", "drinken", "regular", "drink", "drinkt", "drinken", "t"},
        {"To", "accept", "accepteren", "Regular", "accepter", "acceptert", "accepteren", "d"},
        {"To", "allow", "toestaan", "Regular", "toesta", "toestaat", "toestaan", "y"},
        {"To", "answer", "antwoorden", "Regular", "antwoord", "antwoordt", "antwoorten", "d"},
        {"To", "ask", "vragen", "Regular", "varg", "vargt", "vargen", "d"},
        {"To", "believe", "geloven", "Regular", "gelov", "gelovt", "geloven", "d"},
        {"To", "borrow", "lenen", "Regular", "len", "lent", "lenen", "d"},
        {"To", "break", "breken", "Regular", "brek", "brekt", "breken", "t"},
        {"To", "bring", "bregen", "Regular", "breg", "bregt", "bregen", "d"},
        {"To", "budget", "besteden", "Regular", "bested", "bestedt", "besteden", "d"},
        {"To", "buy", "kopen", "Regular", "kop", "kopt", "kopen", "t"},
        {"To", "cancel", "annuleren", "Regular", "annuler", "annulert", "annuleren", "d"},
        {"To", "change", "veranderen", "Regular", "verander", "verandert", "veranderen", "d"},
        {"To", "make", "maken", "Regular", "maak", "maakt", "maken", "t"},
        {"To", "close", "sluiten", "Regular", "sluit", "sluit", "sluiten", "t"},
        {"To", "comb", "kammen", "Regular", "kam", "kamt", "kammen", "d"},
        {"To", "complain", "klagen", "Regular", "klag", "klagt", "klagen", "d"},
        {"To", "cough", "hoesten", "Regular", "hoest", "hoest", "hoesten", "t"},
        {"To", "count", "tellen", "Regular", "tell", "tellt", "tellen", "d"},
        {"To", "cut", "snijden", "Regular", "snijd", "snijdt", "snijden", "d"},
        {"To", "dance", "dansen", "Regular", "dans", "danst", "dansen", "d"},
        {"To", "draw", "tekenen", "Regular", "tek", "tekent", "teken", "t"},
        {"To", "drive", "autorijden", "Regular", "autorijd", "autorijdt", "autorijden", "d"},
        {"To", "eat", "eten", "Regular", "et", "et", "eten", "t"},
        {"To", "explain", "uitleggen", "Regular", "uitlegg", "uitleggt", "uitleggen", "d"},
        {"To", "fall", "vallen", "Regular", "vall", "vallt", "vallen", "d"},
        {"To", "fill", "vullen", "Regular", "vull", "vullt", "vullen", "d"},
        {"To", "finish", "afwerken", "Regular", "afwerk", "afwerkt", "afwerken", "t"},
        {"To", "fit", "aanpassen", "Regular", "aanpass", "aanpasst", "aanpassen", "d"},
        {"To", "fly", "vliegen", "Regular", "vlieg", "vliegt", "vliegen", "d"},
        {"To", "forget", "vergeten", "Regular", "verget", "verget", "vergeten", "t"},
        {"To", "give", "geven", "Regular", "gev", "gevt", "geven", "d"},
        {"To", "go", "gaan", "Regular", "ga", "gaat", "gaan", "y"},
        {"To", "hear", "horen", "Regular", "hor", "hort", "horen", "d"},
        {"To", "hurt", "kwesten", "Regular", "kwest", "kwest", "kwesten", "t"},
        {"To", "know", "weten", "Regular", "wet", "wet", "weten", "t"},
        {"To", "learn", "leren", "Regular", "ler", "lert", "leren", "d"},
        {"To", "leave", "verlaten", "Regular", "verlat", "verlat", "verlaten", "t"},
        {"To", "listen", "luisteren", "Regular", "luister", "luistert", "luisteren", "d"},
        {"To", "live", "leven", "Regular", "lev", "levt", "leven", "d"},
        {"To", "look", "kijken", "Regular", "kijk", "kijkt", "kijken", "t"},
        {"To", "look for", "zoeken", "Regular", "zoek", "zoekt", "zoeken", "t"},
        {"To", "lose", "verliezen", "Regular", "verliez", "verliezt", "verliezen", "t"},
        {"To", "make", "maken", "Regular", "mak", "makt", "maken", "t"},
        {"To", "do", "maken", "Regular", "mak", "makt", "maken", "t"},
        {"To", "need", "nodig heben", "Regular", "nodig heb", "nodig hebt", "nodig heben", "d"},
        {"To", "open", "open maken", "Regular", "open mak", "open makt", "open maken", "t"},
        {"To", "organize", "organiseren", "Regular", "organiser", "organisert", "organiseren", "d"},
        {"To", "pay", "betalen", "Regular", "betal", "betalt", "betalen", "d"},
        {"To", "play", "spelen", "Regular", "spel", "spelt", "spelen", "d"},
        {"To", "put", "neerzeeten", "Regular", "neerzeet", "neerzeet", "neerzeeten", "t"},
        {"To", "put in place", "bevestigen", "Regular", "bevestig", "bevestigst", "bevestigen", "d"},
        {"To", "confirm", "bevestigen", "Regular", "bevestig", "bevestigst", "bevestigen", "d"},
        {"To", "rain", "regen", "Regular", "reg", "regt", "regen", "d"},
        {"To", "read", "lezen", "Regular", "lez", "lezt", "lezen", "t"},
        {"To", "run", "rennen", "Regular", "ren", "rennt", "rennen", "d"},
        {"To", "say", "zeggen", "Regular", "zeg", "zeggt", "zeggen", "d"},
        {"To", "see", "zien", "Regular", "zie", "ziet", "zien", "y"},
        {"To", "sell", "verkopen", "Regular", "verkop", "verkopt", "verkopen", "d"},
        {"To", "send", "sturen", "Regular", "stur", "sturt", "sturen", "d"},
        {"To", "sign", "teken", "Regular", "tek", "tekt", "teken", "t"},
        {"To", "sing", "zingen", "Regular", "zing", "zingt", "zingen", "d"},
        {"To", "sit", "zitten", "Regular", "zitt", "zitt", "zitten", "t"},
        {"To", "sleep", "slapen", "Regular", "slap", "slapt", "slapen", "d"},
        {"To", "smell", "aanruiken", "Regular", "aanruik", "aanruikt", "aanruiken", "t"},
        {"To", "smoke", "roken", "Regular", "rok", "rokt", "roken", "t"},
        {"To", "speak", "spreken", "Regular", "sprek", "sprekt", "spreken", "t"},
        {"To", "spell", "spellen", "Regular", "spell", "spellt", "spellen", "d"},
        {"To", "spend", "uitgeven", "Regular", "uitgev", "uitgevt", "uitgeven", "d"},
        {"To", "stand", "staan", "Regular", "sta", "staat", "staan", "y"},
        {"To", "start", "omtebeginnnen", "Regular", "omtebeginn", "omtebeggint", "omtebegginen", "d"},
        {"To", "begin", "omtebeginnen", "Regular", "omtebegginn", "omtebegginnt", "omtebegginnen", "d"},
        {"To", "study", "omtestuderen", "Regular", "omtestuder", "omtestudert", "omtestuderen", "d"},
        {"To", "succed", "slagen", "Regular", "slag", "slagt", "slagen", "d"},
        {"To", "swim", "zwemmen", "Regular", "zwemm", "zwemmt", "zwemmen", "d"},
        {"To", "take", "nemen", "Regular", "nem", "nemt", "nemen", "d"},
        {"To", "talk", "praten", "Regular", "prat", "prat", "praten", "t"},
        {"To", "taste", "smaken", "Regular", "smak", "smakt", "smaken", "t"},
        {"To", "teach", "onderwizjen", "Regular", "onderwizj", "onderwizjt", "onderwizjen", "d"},
        {"To", "tell", "vertellen", "Regular", "vertell", "vertellt", "vertellen", "d"},
        {"To", "think", "denken", "Regular", "denk", "denkt", "denken", "t"},
        {"To", "translate", "vertalen", "Regular", "vertal", "vertalt", "vertalen", "d"},
        {"To", "travel", "reizen", "Regular", "reiz", "reizt", "reizen", "y"},
        {"To", "try", "proberen", "Regular", "prober", "probert", "proberen", "d"},
        {"To", "turn off", "uitschakelen", "Regular", "uitschakel", "uitschakelt", "uitschakelen", "d"},
        {"To", "turn on", "inschakelen", "Regular", "inschakel", "inschakelt", "inschakelen", "d"},
        {"To", "type", "typen", "Regular", "typ", "typt", "typen", "t"},
        {"To", "understand", "begrijpen", "Regular", "begrijp", "begrjpt", "begrijpen", "t"},
        {"To", "use", "gebruiken", "Regular", "gebruik", "gebruikt", "gebruiken", "t"},
        {"To", "wait", "wachten", "Regular", "wacht", "wacht", "wachten", "t"},
        {"To", "wake up", "wakkerworden", "Regular", "wakkerword", "wakkerwordt", "wakkerworden", "d"},
        {"To", "want", "willen", "Regular", "will", "willt", "willen", "d"},
        {"To", "watch", "bekijken", "Regular", "bekijk", "bekijkt", "bekijken", "t"},
        {"To", "work", "werken", "Regular", "werk", "werkt", "werken", "t"},
        {"To", "worry", "zorgen", "Regular", "zorg", "zorgt", "zorgen", "d"},
        {"To", "write", "schrijven", "Regular", "schrijv", "schrijvt", "schrijven", "d"},
    };

    public static String dutchPro[] = {"Ik", "Jij", "Hij", "Zij", "Het", "U", "Wij", "Jullie", "Zij"};

    public static String dutchSimpleFuture[] = {"ga", "gaat", "gaan"};

    /*
     END DUTCH DEPENDANCIES
     */
    /*
     GERMAN DEPENDANCIES
     */
    public static String germanList[][] = {
        {"To", "be", "sein", "irregular", "bin", "bist", "ist", "sind", "seid", "sind"},
        {"To", "have", "haben", "regular", "habe", "hast", "hat", "habben", "habt", "habben",},
        {"To", "become", "werden", "regular", "werde", "werdst", "wert", "werden", "wert", "werden"},
        {"", "Can", "können", "modal", "kann", "kanst", "kann", "können", "könnt", "können"},
        {"01", "Must", "müssen", "regular", "muss", "must", "muss", "müssen", " müst", "müssen"},
        {"To", "say", "sagen", "regular", "sage", "sagst", "sagt", "sagen", "sagt", "sagen"},
        {"To", "make", "machen", "regular", "mache", "machst", "macht", "machen", "macht", "machen"},
        {"To", "give", "geben", "regular", "gebe", "gebst", "gebt", "geben", "gebt", "geben"},
        {"To", "come", "kommen", "regular", "komme", "kommst", "kommt", "kommen", "kommt", "kommen"},
        {"", "Should", "sollen", "modal", "soll", "sollst", "soll", "sollen", "sollt", "sollen"},
        {"To", "want", "wollen", "modal", "will", "willst", "will", "wollen", "wollt", "wollen"},
        {"To", "go", "gehen", "regular", "gehe", "gehst", "geht", "gehen", "geht", "gehen"},
        {"To", "know", "wissen", "regular", "weiß", "wisst", "weiß", "wissen", "wisst", "wissen"},
        {"To", "see", "sehen", "irregular", "sehe", "siest", "sieht", "sehen", "seht", "sehen"},
        {"To", "allow", "lassen", "irregular", "lass", "lasst", "lass", "lassen", "lasst", "lassen"},
        {"To", "stand", "stehen", "regular", "stehe", "stehst", "steht", "stehen", "steht", "stehen"},
        {"To", "find", "finden", "regular", "finde", "findst", "findt", "finden", "findt", "finden"},
        {"To", "stay", "bleiben", "regular", "bleibe", "bleibst", "bleibt", "bleiben", "bleibt", "bleiben"},
        {"To", "lie", "liegen", "regular", "liege", "liegst", "liegt", "liegen", "liegt", "liegen"},
        {"To", "be called", "heißen", "regular", "heiße", "heißt", "heißt", "heißen", "heißt", "heißen"},
        {"To", "think", "denken", "regular", "denke", "denkst", "dankt", "danken", "dankt", "danken"},
        {"To", "take", "nehmen", "regular", "nehme", "nehmst", "nehmt", "nehmen", "nehmt", "nehmen"},
        {"To", "do", "tun", "irregular", "tue", "tust", "tut", "tun", "tut", "tun",},
        {"", "May", "dürfen", "modal", "darf", "darfst", "darf", "dürfen", "dürft", "dürfen"},
        {"To", "believe", "glauben", "regular", "glaube", "glaubst", "glaubt", "glauben", "glaubt", "glauben"},
        {"To", "stop", "halten", "regular", "halte", "halst", "halt", "halten", "halt", "halten"},
        {"To", "name", "nennen", "regular", "nenne", "nennst", "nennt", "neenen", "nennt", "nennen"},
        {"To", "like", "mögen", "modal", "mag", "magst", "mag", "mögen", "mögt", "mögen"},
        {"To", "show", "zeigen", "regular", "zeige", "zeigst", "zeigt", "zeigen", "zeigt", "zeigen"},
        {"To", "lead", "führen", "regular", "führe", "führst", "führt", "führen", "führt", "führen"},
        {"To", "speak", "sprechen", "regular", "spreche", "sprechst", "sprecht", "sprechen", "sprecht", "sprechen"},
        {"To", "bring", "bringen", "regular", "bringe", "bringst", "bringt", "bringen", "bringt", "bringen"},
        {"To", "live", "leben", "regular", "lebe", "lebst", "lebt", "leben", "lebt", "leben"},
        {"To", "drive", "fahren", "irregular", "fahre", "fährst", "färt", "fahren", "fart", "fahren"},
        {"To", "have an opinion", "meinen", "regular", "meine", "meinst", "meint", "meinen", "meint", "meinen"},
        {"To", "ask", "fragen", "regular", "frage", "fragst", "fragt", "fragen", "fragt", "fragen"},
        {"To", "know", "kennen", "regular", "kenne", "kennst", "kennt", "kennen", "kennt", "kennen"},
        {"To", "be valid", "gelten", "regular", "gelte", "geltst", "gelten", "gelt", "gelten"},
        {"To", "place", "stellen", "regular", "stelle", "stellst", "stellt", "stellen", "stellt", "stellen"},
        {"To", "play", "spielen", "regular", "spiele", "spielst", "spielt", "spielen", "spielt", "spielen"},
        {"To", "work", "arbeiten", "regular", "arbeite", "arbeitest", "arbeitet", "arbeiten", "arbeitet", "arbeiten"},
        {"To", "need", "brauchen", "regular", "brauche", "brauchst", "braucht", "brauchen", "braucht", "brauchen"},
        {"To", "follow", "folgen", "regular", "folge", "folgst", "folgt", "folgen", "folgt", "folgen"},
        {"To", "learn", "learnen", "regular", "learne", "learnst", "learnt", "learnen", "learnt", "learnen"},
        {"To", "exist", "bestehen", "regular", "bestehe", "bestehest", "bestehet", "bestehen", "besteht", "bestehen"},
        {"To", "understand", "verstehen", "regular", "verstehe", "verstehst", "versteht", "verstehen", "versteht", "verstehen"},
        {"To", "set", "setzen", "regular", "setze", "setzst", "setzt", "setzen", "setzt", "setzen"},
        {"To", "receive", "bekommen", "regular", "bekomme", "bekommst", "bekommt", "bekommen", "bekommt", "bekommen"},
        {"To", "begin", "beginnen", "regular", "beginne", "beginnst", "beginnt", "beginnen", "beginnt", "beginnen"},
        {"To", "tell", "erzählen", "regular", "erzähle", "erzählst", "erzählt", "erzählen", "erzählt", "erzählen"},
        {"To", "try", "versuchen", "regular", "versuche", "versuchst", "versucht", "versuchen", "versucht", "versuchen"},
        {"To", "write", "schreiben", "regular", "schreibe", "schreibst", "schreibt", "schreiben", "schreibt", "schreiben"},
        {"To", "run", "laufen", "regular", "laufe", "laufst", "lauft", "laufen", "lauft", "laufen"},
        {"To", "explain", "erklären", "reguar", "erkläre", "erklärst", "erklärt", "erklären", "erklärt", "erklären"},
        {"To", "correspond", "entsprechen", "regular", "entspreche", "entsprechst", "entsprecht", "entsprechen", "entsprecht", "entsprechen"},
        {"To", "sit", "sitzen", "regular", "sitze", "sitzt", "sitzt", "sitzen", "sitzt", "sitzen"},
        {"To", "pull", "ziehen", "regular", "ziehe", "ziehst", "zieht", "ziehen", "zieht", "ziehen"},
        {"To", "seem", "scheinen", "regular", "scheine", "scheinst", "scheint", "scheinen", "scheint", "scheinen"},
        {"To", "fall", "fallen", "irregular", "falle", "fällst", "fällt", "fallen", "fallt", "fallen"},
        {"To", "belong", "gehören", "regular", "gehören", "gehörst", "gehört", "gehören", "gehört", "gehören"},
        {"To", "originate", "entstehen", "regular", "entstehe", "entstehst", "entsteht", "entstehen", "entsteht", "entstehen"},
        {"To", "recieve", "enthalten", "irregular", "halte", "hältst", "hält", "halten", "hält", "halten"},
        {"To", "meet", "treffen", "irregular", "treffe", "trefft", "trefft", "treffen", "trefft", "treffen"},
        {"To", "search", "suchen", "regular", "suche", "suchst", "sucht", "suchen", "sucht", "suchen"},
        {"To", "lay", "legen", "regular", "lege", "legst", "legt", "legen", "legt", "legen"},
        {"To", "introduce", "vorstellen", "regular", "vorstelle", "vorstellst", "vorstellt", "vorstellen", "vorstellt", "vorstellen"},
        {"To", "trade", "handeln", "regular", "handele", "handelst", "handelt", "handeln", "handelt", "handeln"},
        {"To", "achieve", "erreichen", "regular", "erreiche", "erreichst", "erreicht", "erreichen", "erreicht", "erreichen"},
        {"To", "wear", "tragen", "regular", "trage", "tragst", "tragt", "tragen", "tragt", "tragen"},
        {"To", "manage", "schaffen", "regular", "schaffe", "schaffst", "schafft", "schaffen", "schafft", "schaffen"},
        {"To", "read", "lesen", "irregular", "lese", "liest", "liest", "lesen", "lest", "lesen"},
        {"To", "lose", "verlieren", "regular", "verliere", "verlierst", "verliert", "verlieren", "verliert", "verlieren"},
        {"To", "depict", "darstellen", "regular", "darstelle", "darstellst", "darstellt", "darstellen", "darstellt", "darstellen"},
        {"To", "recognize", "erkennen", "regular", "erkenne", "erkennst", "erkennt", "erkennen", "erkennt", "erkennen"},
        {"To", "develop", "entwickeln", "regular", "entwickele", "entwickelst", "entwickelt", "entwickeln", "entwickelt", "entwickeln"},
        {"To", "talk", "reden", "regular", "rede", "redst", "redt", "reden", "redt", "reden"},
        {"To", "look", "aussehen", "irregular", "aussehe", "ausiest", "aussieht", "aussehen", "ausseht", "aussehen"},
        {"To", "appear", "erscheinen", "regular", "erscheine", "erscheinst", "erscheint", "erscheinen", "erscheint", "erscheinen"},
        {"To", "form", "bilden", "regular", "bilde", "bildst", "bildt", "bilden", "bildt", "bilden"},
        {"To", "begin", "anfangen", "irregular", "anfange", "anfängst", "anfängt", "anfangen", "anfangt", "anfangen"},
        {"To", "expect", "erwarten", "regular", "erwarte", "erwartest", "erwartet", "erwarten", "erwartet", "erwarten"},
        {"To", "live", "whonen", "regular", "whone", "whonst", "whont", "whonen", "whont", "whonen"},
        {"To", "affect", "betreffen", "regular", "betreffe", "betreffst", "betrefft", "betreffen", "betrefft", "betreffen"},
        {"To", "wait", "warten", "regular", "warte", "wartest", "wartet", "warten", "wartet", "warten"},
        {"To", "elapse", "vergehen", "regular", "vergehe", "vergehst", "vergeht", "vergehen", "vergeht", "vergehen"},
        {"To", "help", "helfen", "irregular", "helfe", "hilfst", "hilft", "helfen", "helft", "helfen"},
        {"To", "win", "gewinnen", "regular", "gewinne", "gewinnst", "gewinnt", "gewinnen", "gewinnt", "gewinnen"},
        {"To", "close", "schließen", "regular", "schließe", "schließt", "schließt", "schließen", "schließt", "schließen"},
        {"To", "feel", "fühlen", "regular", "fühle", "fülst", "fühlt", "fühlen", "fühlt", "fühlen"},
        {"To", "offer", "bieten", "regular", "biete", "biest", "biet", "bieten", "biet", "bieten"},
        {"To", "interest", "interessieren", "regular", "interessiere", "interessierst", "interessiert", "interessieren", "interessiert", "interessieren"},
        {"To", "remember", "erinnern", "regular", "erinnere", "erinnerst", "erinnert", "erinnern", "erinnert", "erinnern"},
        {"To", "result", "ergeben", "regular", "ergebe", "ergebst", "ergebt", "ergeben", "ergebt", "ergeben"},
        {"To", "offer", "anbieten", "regular", "anbiete", "anbietst", "anbiet", "anbieten", "anbiet", "anbieten"},
        {"To", "study", "studieren", "regular", "studiere", "studierst", "studiert", "studieren", "studiert", "studieren"},
        {"To", "connect", "verbinden", "regular", "verbinde", "verbindst", "verbindt", "verbinden", "verbindt", "verbinden"},
        {"To", "look at", "ansehen", "irregular", "ansehe", "ansiest", "ansieht", "ansehen", "anseht", "ansehen"},
        {"To", "be missing", "fehlen", "regular", "fehle", "fehlst", "fehlt", "fehlen", "fehlt", "fehlen"},
        {"To", "mean", "bedeuten", "regular", "bedeute", "bedeutst", "bedeut", "bedeuten", "bedeut", "bedeuten"},
        {"To", "compare", "vergleichen", "regular", "vergleiche", "vergleichst", "vergleicht", "vergleichen", "vergleicht", "vergleichen"},
        {"To", "collect", "abholen", "regular", "abhole", "abholst", "abholt", "abholen", "abholt", "abholen"},
        {"To", "change", "ändern", "regular", "ändere", "änderst", "ändert", "ändern", "ändert", "ändern"},
        {"To", "arrive", "ankommen", "regular", "ankomme", "ankommst", "ankommt", "ankommen", "ankommt", "ankommen"},
        {"To", "answer", "antworten", "regular", "antworte", "antwortst", "antwort", "antworten", "antwort", "antworten"},
        {"To", "breathe", "atmen", "regular", "atme", "atmest", "atmet", "atmen", "atmet", "atmen"},
        {"To", "stop", "aufhalten", "irregular", "aufhalte", "aufhalst", "aufhalt", "aufhalten", "aufhalt", "aufhalten"},
        {"To", "open", "aufmachen", "regular", "aufmache", "aufmachst", "aufmacht", "aufmachen", "aufmacht", "aufmachen"},
    };

    public static String germanPro[] = {"Ich", "Du", "Er", "Sie", "Es", "Wir", "Ihr", "Sie", "sie"};

    public static String germanFutre[] = {"Werde", "Wirst", "Wird", "Wirden", "Wirdet", "Wirden"};

    /*
     END GERMAN DEPENDANCIES
     */
    /*
     SPANISH DEPENDANCIES
     */
    public static String spanishList[][] = {
        {"To", "be", "Ser", "Irregular", "Soy", "Eres", "Es", "Somos", "Son"},
        {"To", "have", "Tener", "Irregular", "Tengo", "Tienes", "Tiene", "Tenemos", "Tienen"},
        {"", "Can", "Poder", "Irregular", "Puedo", "Puedes", "Puede", "Podemos", "Pueden"},
        {"", "Must", "Tener que", "Regular", "Tengo que", "Tienes que", "Tiene que", "Tenemos que", "Tienen que"},
        {"To", "say", "Decir", "Irregular", "Digo", "Dices", "Dice", "Decimos", "Dicen"},
        {"To", "do", "Hacer", "Irregular", "Hago", "Haces", "Hace", "Hace", "Hacemos", "Hacen"},
        {"To", "give", "Dar", "Irregular", "Doy", "Das", "Da", "Damos", "Dan"},
        {"To", "come", "Venir", "Irregular", "Vengo", "Viene", "Viene", "Venimos", "Vienen"},
        {"", "Should", "Deber", "Regular", "Debo", "Debes", "Debe", "Debimos", "Deben"},
        {"To", "wake up", "Despertarse", "Reflexive", "Me Despierto", "Te Despiertas", "Se Despierta", "Nos Despertamos", "Se Despiertan"},
        {"To", "cook", "Cocinar", "Regular", "Cocino", "Cocinas", "Cocina", "Cocinamos", "Cocinan"},
        {"To", "put", "Poner", "Irregular", "Pongo", "Pongas", "Ponga", "Ponemos", "Pongan"},
        {"To", "go", "Ir", "Irregular", "Voy", "Vas", "Va", "Vamos", "Van"},
        {"To", "run", "Correr", "Regular", "Corro", "Corres", "Corre", "Corremos", "Corren"},
        {"To", "bring", "Traer", "Irregular", "Traigo", "Traes", "Trae", "Traemos", "Traen"},
        {"To", "lose", "Perder", "Irregular", "Pierdo", "Pierdes", "Pierde", "Perdemos", "Pierden"},
        {"To", "know", "Saber", "Irregular", "Sé", "Sabes", "Sabe", "Sabemos", "Saben"},
        {"To", "see", "Ver", "Irregular", "Veo", "Ves", "Ve", "Vemos", "Ven"},
        {"To", "believe", "Creer", "Irregular", "Creo", "Crees", "Cree", "Creemos", "Creen"},
        {"To", "pass time", "Pasar", "Regular", "Paso", "Pasas", "Pasa", "Pasamos", "Pasan", "Pasan"},
        {"To", "call", "Llamar", "Regular", "Llamo", "Llamas", "Llama", "Llamamos", "Llaman", "Llaman"},
        {"To", "stay", "Quedar", "Regular", "Quedo", "Quedas", "Queda", "Quedamos", "Quedan", "Quedan"},
        {"To", "want", "Querer", "Irregular", "Quiero", "Quieres", "Quiere", "Queremos", "Quieren", "Quieren"},
        {"To", "seem", "Parecer", "Irregular", "Parezco", "Pareces", "Parece", "Parecemos", "Parecen", "Paracen"},
        {"To", "speak", "Hablar", "Regular", "Hablo", "Hablas", "Habla", "Hablamos", "Hablan", "Hablan"},
        {"To", "carry", "Llevar", "Regular", "Llevo", "Llevas", "Lleva", "Llevamos", "Llevan", "Llevan"},
        {"To", "leave", "Dejar", "Regular", "Dejo", "Dejas", "Deja", "Dejamos", "Dejan", "Dejan"},
        {"To", "follow", "Seguir", "Irregular", "Sigo", "Sigues", "Sigue", "Seguimos", "Siguen", "Siguen"},
        {"To", "find", "Encontrar", "Irregular", "Encuentro", "Encuentras", "Encuentra", "Encontramos", "Encuentran", "Encuentran"},
        {"To", "think", "Pensar", "Irregular", "Pienso", "Piensas", "Piensa", "Pensamos", "Piensan", "Piensan"},
        {"To", "go out", "Salir", "Irregular", "Salgo", "Sales", "Sale", "Salimos", "Salen", "Salen"},
        {"To", "live", "Vivir", "Regular", "Vivo", "Vives", "Vive", "Vivimos", "Viven", "Viven"},
        {"To", "watch", "Mirar", "Regular", "Miro", "Miras", "Mira", "Miramos", "Miran", "Miran"},
        {"To", "look for", "Buscar", "Regular", "Busco", "Buscas", "Busca", "Buscamos", "Buscan", "Buscan"},
        {"To", "hope", "Esperar", "Regular", "Espero", "Esperas", "Espera", "Esperamos", "Esperan", "Esperan"},
        {"To", "feel", "Sentir", "Irregular", "Siento", "Sientes", "Siente", "Sentimos", "Sienten", "Sienten"},
        {"To", "work", "Trabajar", "Regular", "Trabajo", "Trabajas", "Trabaja", "Trabajamos", "Trabajan", "Trabajan"},
        {"To", "write", "Escribir", "Regular", "Escribo", "Escribes", "Escribe", "Escribimios", "Escriben", "Escriben"},
        {"To", "produce", "Producir", "Irregular", "Produzco", "Produces", "Produce", "Producimos", "Producen", "Producen"},
        {"To", "finish", "Terminar", "regular", "Termino", "Terminas", "Termina", "Terminamos", "Terminan", "Terminan"},
        {"To", "remember", "Recordar", "Irregular", "Recuerdo", "Recuerdas", "Recuerda", "Recordamos", "Recuerdan", "Recuerdan"},
        {"To", "take out", "Sacar", "Regular", "Saco", "Sacas", "Saca", "Sacamos", "Sacan", "Sacan"},
        {"To", "need", "Necesitar", "Regular", "Necesito", "Necesitas", "Necesita", "Necesitamos", "Necesitan", "Necesitan"},
        {"To", "read", "Leer", "Regular", "Leo", "Lees", "Lee", "Leemos", "Leen", "Leen"},
        {"To", "open", "Abrir", "Regular", "Abro", "Abres", "Abre", "Abrimos", "Abren", "Abren"},
        {"To", "hear", "Oir", "Irregular", "Oigo", "Oyes", "Oye", "Oimos", "Oyen", "Oyen"},
        {"To", "consider", "Considerar", "Regular", "Considero", "Consideras", "Considera", "Consideramos", "Consideran", "Consideran"},
        {"To", "win", "Ganar", "Regular", "Gano", "Ganas", "Gana", "Ganamos", "Ganan", "Ganan"},
        {"To", "die", "Morir", "Irregular", "Muero", "Mueres", "Muere", "Morimos", "Mueren", "Mueren"},
        {"To", "ask", "Preguntar", "Regular", "Pregunto", "Preguntas", "Pregunta", "Preguntamos", "Preguntan", "Preguntan"},
        {"To", "play", "Tocar", "Regular", "Toco", "Tocas", "Toca", "Tocamos", "Tocan", "Tocan"},
        {"To", "study", "Estudiar", "Regular", "Estudio", "Estudias", "Estudia", "Estudiamos", "Estudian", "Estudian"},
        {"To", "be born", "Nacer", "Irregular", "Nazco", "Naces", "Nace", "Nacemos", "Nacen", "Nacen"},
        {"To", "pay", "Pagar", "Regular", "Pago", "Pagas", "Paga", "Pagamos", "Pagan", "Pagan"},
        {"To", "help", "Ayudar", "Regular", "Ayudo", "Ayudas", "Ayuda", "Ayudamos", "Ayudan", "Ayudan"},
        {"To", "listen", "Escuchar", "regular", "Escucho", "Escuchas", "Escucha", "Escuchamos", "Escuchan", "Escuchan"},
        {"To", "offer", "Ofrecer", "Irregular", "Ofrezco", "Ofreces", "Ofrece", "Ofrecemos", "Ofrecen", "Ofrecen"},
        {"To", "use", "Usar", "Regular", "Uso", "Usas", "Usa", "Usamos", "Usan", "Usan"},
        {"To", "permit", "Permitir", "irregular", "Permito", "Permites", "Permite", "Permitimos", "Permiten", "Permiten"},
        {"To", "appear", "Aparecer", "irregular", "Aparezco", "Apareces", "Aparece", "Aparecemos", "Aparecen", "Aparecen"},
        {"To", "get", "Conseguir", "regular", "Consigo", "Consigues", "Consigue", "Consegimos", "Consiguen", "Consiguen"},
        {"To", "begin", "comenzar", "regular", "Comienzo", "Comienzas", "Comienza", "Comenzamos", "Comienzan", "Comienzan"},
        {"To", "serve", "servir", "regular", "Sirvo", "Sirves", "Sirve", "Servimos", "Sirven", "Sirven"},
        {"To", "maintain", "Mantener", "regular", "Mantego", "Mantienes", "Mantiene", "Mantenemos", "Mantienen", "Mantienen"},
        {"To", "turn out", "Resultar", "regular", "Resulto", "Resultas", "Resulta", "Resultamos", "Resultan", "Resultan"},
        {"To", "change", "Cambiar", "regular", "Cambio", "Cambias", "Cambia", "Cambiamos", "Cambian", "Cambian"},
        {"To", "try", "Intentar", "irregular", "Intentar", "Intentas", "Intenta", "Intentamos", "Intentan", "Intentan"},
        {"To", "like", "Gustar", "regular", "Gusto", "Gustas", "Gusta", "Gustamos", "Gustan", "Gustan"},
        {"To", "fall", "Caer", "regular", "Caigo", "Caes", "Cae", "Caemos", "Caen", "Caen"},
        {"To", "create", "Crear", "regular", "Creo", "Creas", "Crea", "Creamos", "Crean", "Crean"},
        {"To", "fulfil", "Cumplir", "irregular", "Cumplo", "Cumples", "Cumple", "Cumplimos", "Cumplen", "Cumplen"},
        {"To", "return", "Volver", "irregular", "Vuelvo", "Vuelves", "Vuelve", "Vuelve", "Volvemos", "Vuelven", "Vuelven"},
        {"To", "accept", "Aceptar", "Regular", "Acepto", "Aceptas", "Acepta", "Aceptamos", "Aceptan", "Aceptan"},
        {"To", "borrow", "Prestar", "Regular", "Presto", "Prestas", "Presta", "Prestamos", "Prestan", "Prestan"},
        {"To", "break", "Romper", "Regular", "Rompo", "Rompas", "Rompa", "Rompamos", "Rompan", "Rompan"},
        {"To", "cancel", "Cancelar", "Regular", "Cancelo", "Cancelas", "Cancela", "Cancelamos", "Cancelan", "Cancelan"},
        {"To", "clean", "Limpiar", "Regular", "Limpio", "Limpias", "Limpia", "Limpiamos", "Limpian", "Limpian"},
        {"To", "count", "Contar", "Regular", "Conto", "Contas", "Conta", "Contamos", "Contan", "Contan"},
        {"To", "cut", "Cortar", "Regular", "Corto", "Cortas", "Corta", "Cortamos", "Cortan", "Cortan"},
        {"To", "dance", "Bailar", "Regular", "Bailo", "Bailas", "Baila", "Bailamos", "Bailan", "Bailan"},
        {"To", "draw", "Dibujar", "Regular", "Dibujo", "Dibujas", "Dibuja", "Dibujamos", "Dibujan", "Dibujan"},
        {"To", "cry", "Llorar", "Regular", "Lloro", "Lloras", "Llora", "Lloraamos", "Lloran", "Lloran"},
        {"To", "forget", "Olvidar", "Regular", "Olvido", "Olvidas", "Olvida", "Olvidamos", "Olvidan", "Olvidan"},
        {"To", "play", "Jugar", "Irregular", "Juego", "Juegas", "Juega", "Jugamos", "Juegan", "Juegan"},
        {"To", "organize", "Organizar", "Regular", "Organizo", "Organizas", "Organiza", "Organizamos", "Organizan", "Organizan"},
        {"To", "sing", "Cantar", "Regular", "Canto", "Cantas", "Canta", "Cantamos", "Cantan", "Cantan"},
        {"To", "smoke", "Fumar", "Regular", "Fumo", "Fumas", "Fuma", "Fumamos", "Fuman", "Fuman"},
        {"To", "swim", "Nadar", "Regular", "Nado", "Nadas", "Nada", "Nadamos", "Nadan", "Nadan"},
        {"To", "travel", "Viajar", "Regular", "Viajo", "Viajas", "Viajamos", "Viajan", "Viajan"},
        {"To", "allow", "Dejar", "Regular", "Dejo", "Dejas", "Deja", "Dejamos", "Dejan", "Dejan"},
        {"To", "explain", "Explicar", "Regular", "Explico", "Explicas", "Explica", "Explicamos", "Explican", "Explican"},
        {"To", "turn off", "Apagar", "Regual", "Apago", "Apagas", "Apaga", "Apagamos", "Apagan", "Apagan"},
        {"To", "turn on", "Encender", "Irregular", "Enciendo", "Enciendes", "Enciende", "Encendemos", "Encienden", "Encienden"},
        {"To", "teach", "Enseñar", "Regular", "Enseño", "Enseñas", "Enseña", "Enseñamos", "Enseñan", "Enseñan"},
        {"To", "spend", "Gastar", "Regular", "Gasto", "Gastas", "Gasta", "Gastamos", "Gastan", "Gastan"},
        {"To", "visit", "Visitar", "Regular", "Visito", "Visitas", "Visita", "Visitamos", "Visitan", "Visitan"},
        {"To", "sit", "Sentar", "Irregular", "Siento", "Sientas", "Sienta", "Sentamos", "Sientan", "Sientan"},
        {"To", "reply", "Responder", "Regular", "Respondo", "Respones", "Responde", "Respondemos", "Responden", "Responden"},
        {"To", "translate", "Traducir", "Irregular", "Traduzco", "Traduces", "Traduce", "Traducemos", "Traducen", "Traducen"},
        {"To", "vomit", "Vomitar", "Regular", "Vomito", "Vomitas", "Vomita", "Vomitamos", "Vomitan", "Vomitan"},
        {"To", "sell", "Vender", "Regular", "Vendo", "Vendes", "Vende", "Vendemos", "Venden", "Venden",},
        {"To", "trip", "Tropezar", "Irregular", "Tropiezo", "Tropiezas", "Tropieza", "Tropezamos", "Tropiezan", "Tropiezan"},
        {"To", "confess", "Confesar", "Irregular", "Confieso", "Confiesas", "Confiesa", "Confesamos", "Confiesan", "Confiesan"},
        {"To", "love", "Amar", "Regular", "Amo", "Amas", "Ama", "Amamos", "Aman", "Aman"},
        {"To", "freeze", "Helar", "Irregular", "Hielo", "Hielas", "Hiela", "Helamos", "Hielan", "Hielan"},
        {"To", "fake", "Fingir", "Irregular", "Finjo", "Finges", "Finge", "Fingimos", "Fingen", "Fingen"},
        {"To", "explore", "Explorar", "Regular", "Exploro", "Exploras", "Explora", "Exploramos", "Exploran", "Exploran"},
        {"To", "raise", "Criar", "Regular", "Crio", "Crias", "Cira", "Criamos", "Crian", "Crian"}, // has accent on i
        {"To", "kiss", "Besar", "Regular", "Beso", "Besas", "Besa", "Besamos", "Besan", "Besan"},
        {"To", "stop", "Cesar", "Regular", "Ceso", "Cesas", "Cesa", "Cesamos", "Cesan", "Cesan"},
        {"To", "provoke", "Provocar", "Regular", "Provoco", "Provocas", "Provoca", "Provocamos", "Proovocan", "Provocan"},
        {"To", "illustrate", "Ilustrar", "Regular", "Ilustro", "Ilustras", "Ilustra", "Ilustramos", "Ilustran", "Ilustran"},
        {"To", "interest", "Interesar", "Regular", "Intereso", "Interesas", "Interesa", "Interesamos", "Interesan", "Interesan"},
        {"To", "inspire", "Enamorar", "Regular", "Enamoro", "Ensamoras", "Enamora", "Enamoramos", "Enamoran", "Enamoran"},
        {"To", "get", "Obtener", "Irregular", "Obtengo", "Obtienes", "Obtiene", "Obtenemos", "Obtienen", "Obtienen"},
        {"To", "put makeup on", "Maquillar", "Regular", "Maquillo", "Maquillas", "Maquilla", "Maquillamios", "Maquillan", "Maquillan"},
        {"To", "invade", "Invadir", "Regular", "Invado", "Invades", "Invade", "Invadimos", "Invaden", "Invaden"},
        {"To", "laugh", "Reir", "Regular", "Río", "Ríes", "Ríe", "Reímos", "Ríen", "Ríen"}, //has acccent on i
        {"To", "note", "Notar", "Regular", "Noto", "Notas", "Nota", "Notamos", "Notan", "Notan"},
        {"To", "throw", "Echar", "Regular", "Echo", "Echas", "Echa", "Echamos", "Echan", "Echan"},
        {"To", "wield", "Ejercer", "Irregular", "Ejerzo", "Ejerces", "Ejerce", "Ejercemos", "Ejercen", "Ejercen"},
        {"To", "swear", "Jurar", "Regular", "Juro", "Juras", "Jura", "Juramos", "Juran", "Juran"},
        {"To", "hate", "Odiar", "Regular", "Odio", "Odias", "Odia", "Odiamos", "Odian", "Odian"},
        {"To", "deny", "Negar", "Irregular", "Niego", "Niegas", "Niega", "Negamos", "Niegan", "Niegan"},
        {"To", "congratulate", "Felicitar", "Regular", "Felicito", "Felicitas", "Felicita", "Felicitamos", "Felicitan", "Felicitan"},
        {"To", "age", "Envejecer", "Irregular", "Envejezco", "Envejeces", "Envejece", "Envejecemos", "Envejecen", "Envejecen"},
        {"To", "enter", "Entrar", "Regular", "Entro", "Entras", "Entra", "Entramos", "Entran", "Entran"},
        {"To", "cross", "Atravesar", "Irregular", "Atravieso", "Atraviesas", "Atraviesa", "Atravesamos", "Atrviesan", "Atraviesan"},
        {"To", "decorate", "Adornar", "Regular", "Adorno", "Adornas", "Adorna", "Adornamos", "Adornan", "Adornan"},
        {"To", "please", "Agradar", "Regular", "Agrado", "Agradas", "Agrada", "Agradamos", "Agradan", "Agradan"},
        {"To", "beat", "Batir", "Regular", "Bato", "Bates", "Bate", "Batemos", "Baten", "Baten"},
        {"To", "lie down", "Yacer", "Irregular", "Yazco", "Yaces", "Yace", "Yacemos", "Yacen", "Yacen"},
        {"To", "pray", "Rezar", "Regular", "Rezo", "Rezas", "Reza", "Rezamos", "Rezan", "Rezan"},
        {"To", "reserve", "Reservar", "Regualr", "Reservo", "Reservas", "Reserva", "Reservamos", "Reservan", "Reservan"},
        {"To", "set up", "Oponer", "Irregular", "Opongo", "Opones", "Opone", "Oponemos", "Oponen", "Oponen"},
        {"To", "anticipate", "Prever", "Irregular", "Preveo", "Prevés", "Prevé", "Prevemos", "Prevén", "Prevén"},
        {"To", "puncture", "Picar", "Regualr", "Pico", "Picas", "Pica", "Picamos", "Pican", "Pican"},
        {"To", "pick up", "Recoger", "Irregular", "Recojo", "Recoges", "Recoge", "Recogemos", "Recogen", "Recogen"},
        {"To", "purify", "Purificar", "Regular", "Purifico", "Purificas", "Purifica", "Purificamos", "Purifican", "Purifican"},
        {"To", "obey", "Obedecer", "Irregular", "Obedezco", "Obedeces", "Obedece", "Obedecemos", "Obedecen", "Obedecen"},
        {"To", "recycle", "Reciclar", "Regular", "Reciclo", "Reciclas", "Recicla", "Reciclamos", "Reciclan", "Reciclan"},
        {"To", "pardon", "Perdonar", "Regular", "Perdono", "Perdonas", "Perdona", "Perdonamos", "Perdonan", "Perdonan"},
        {"To", "burn", "Quemar", "Regular", "Quemo", "Quemas", "Quema", "Quemamos", "Queman", "Queman"},
        {"To", "reveal", "Revelar", "Regular", "Revelo", "Revelas", "Revela", "Revelamos", "Revelan", "Revelan"},
        {"To", "require", "Requerir", "Irregular", "Requiero", "Requieres", "Requiere", "Requerimos", "Requieren", "Requieren"},
        {"To", "tell off", "Reñir", "Irregular", "Riño", "Riñes", "Riñe", "Reñimos", "Riñen", "Riñen"},
        {"To", "ring", "Sonar", "Irregular", "Sueno", "Suenas", "Suena", "Sonamos", "Suenan", "Suenan"},
        {"To", "dream", "Soñar", "Irregular", "Sueño", "Sueñas", "Sueña", "Soñamos", "Sueñan", "Sueñan"},
        {"To", "violate", "Violar", "Regular", "Violo", "Violas", "Viola", "Violamos", "Violan", "Violan"},
        {"To", "stop", "Parar", "Regular", "Paro", "Paras", "Para", "Paramos", "Paran", "Paran"},
        {"To", "intoxicate", "Emorrachar", "Regular", "Emorracho", "Emorrachas", "Emoracha", "Emorachamos", "Emorachan", "Emorachan"},
        {"To", "navigate", "Navegar", "Regular", "Navego", "Navegas", "Navega", "Navegamos", "Navegan", "Navegan"},
        {"To", "snow", "Nevar", "Irregular", "Nievo", "Nievas", "Nieva", "Nevamos", "Nievan", "Nievan"},
        {"To", "long for", "Anhelar", "Regular", "Anhelo", "Anhelas", "Anhela", "Anhelamos", "Anhelan", "Anhelan"},
        {"To", "startle", "Chocar", "Regular", "Choco", "Chocas", "Choca", "Chocamos", "Chocan", "Chocan"},
        {"To", "convince", "Convencer", "Irregular", "Convenzo", "Convences", "Convence", "Convencemos", "Convencen", "Convencen"},
        {"To", "get in a vehicle", "Abordar", "Regular", "Abordo", "Abordas", "Aborda", "Abordamos", "Abordan", "Abordan"},
        {"To", "remove", "Quitar", "Regular", "Quito", "Quitas", "Quita", "Quitamos", "Quitan", "Quitan"},
        {"To", "join", "Juntar", "Regular", "Junto", "Juntas", "Junta", "Juntamos", "Juntan", "Juntan"},
        {"To", "direct", "Dirigir", "Irregular", "Dirijo", "Diriges", "Dirige", "Dirigimos", "Dirigen", "Dirigen"},
        {"To", "extinguish", "Extinguir", "Irregular", "Extingo", "Extingues", "Extingue", "Extinguimos", "Extinguen", "Extinguen"},
        {"To", "hang", "Colgar", "Irregular", "Cuelgo", "Cuelgas", "Cuelga", "Cuelgamos", "Cuelgan", "Cuelgan"},
        {"To", "develope", "Desarrollar", "Regular", "Desarrollo", "Desarrollas", "Desarrolla", "Deasrrollamos", "Desarrollan", "Desarrollan"},
        {"To", "consent", "Consentir", "Irregular", "Consiento", "Consientes", "Consiente", "Consentimos", "Consienten", "Consienten"},
        {"To", "endure", "Aguantar", "Regular", "Aguanto", "Aguantas", "Aguanta", "Aguantamos", "Aguantan", "Aguantan"},
        {"To", "happen", "Acontecer", "Irregular", "Acontezco", "Aconteces", "Acontece", "Acontecemos", "Acontecen", "Acontecen"},
        {"To", "support", "Apoyar", "Regular", "Apoyo", "Apoyas", "Apoya", "Apoyamos", "Apoyan", "Apoyan"},
        {"To", "heat up", "Calentar", "Irregular", "Caliento", "Calientas", "Calienta", "Calentamos", "Calienten", "Calineten"},
        {"To", "attack", "Atacar", "Regular", "Ataco", "Atacas", "Ataca", "Atacamos", "Atacan", "Atacan"},
        {"To", "amuse", "Divertir", "Irregular", "Divierto", "Diviertes", "Divierte", "Divietimos", "Dievierten", "Divierten"},
        {"To", "dedicate", "Dedicar", "Regular", "Dedico", "Dedicas", "Dedica", "Dedicamos", "Dedican", "Dedican"},
    };

    public static String spanishPro[] = {"Yo", "Tu", "El", "Ella", "Nosotros", "Ellos", "Ellas"};
    /*
     END SPANISH DEPENDANCIES
     */

    /*
     LITHUANIAN DEPENDANCIES
     */
    public static String lithuanianList[][] = {
        {"To", "be", "Būti", "Irregular", "esu", "esi", "yra", "esame", "esate"},
        {"To", "go", "Eiti", "Regular", "einu", "eimi", "eina", "einame", "einate"},
        {"To", "walk", "Eiti", "Regular", "einu", "eimi", "eina", "einame", "einate"},
        {"To", "give", "Duoti", "Regular", "duodu", "duodi", "duoda", "duodame", "duoate"},
        {"To", "talk", "Kalbėti", "Regular", "kalbu", "kalbi", "kalba", "kalbame", "kalbate"},
        {"To", "speak", "Kalbėti", "Regular", "kalbu", "kalbi", "kalba", "kalbame", "kalbate"},
        {"To", "live", "Gyventi", "Regular", "gyvenu", "gyveni", "gyvena", "gyvaname", "gyvnate"},
        {"To", "take", "Imti", "Regular", "imu", "imi", "ima", "imame", "imate"},
        {"To", "get", "Gauti", "Regular", "gaunu", "gauni", "gauna", "gauname", "gaunate"},
        {"To", "buy", "Pirkti", "Regular", "pirknu", "pirkni", "pirkna", "pirkname", "pirkate"},
        {"To", "wait", "Laukti", "Regular", "laukiu", "lauki", "laukia", "laukiame", "laukiate"},
        {"To", "hate", "Nekęsti", "Regular", "nekenčiu", "nekenči", "nekenčia", "nekenčiame", "nekenčite"},
        {"To", "need", "Reiketi", "Regular", "reikenu", "reikeni", "reikena", "reikename", "reikenate"},
        {"To", "be liked", "Patikti", "Regular", "patiknu", "patikni", "patikna", "patikname", "patiknate"},
        {"To", "appeal", "Patikti", "Regular", "patiknu", "patikni", "patikna", "patikname", "patiknate"},
        {"To", "to call", "Skambinti", "Regular", "skambinu", "skambini", "skambinta", "skambiname", "skambinate"},
        {"To", "command", "Liepti", "Regular", "lieptu", "liepti", "liepta", "lieptame", "lieptate"},
        {"To", "allow", "Liesti", "Regular", "liestu", "liesti", "liesta", "liestame", "liestate"},
        {"To", "run", "bėgti", "Regular", "bėgtu", "bėgti", "bėgta", "bėgtame", "bėgtate"},
        {"To", "hold", "laikyti", "Regular", "laikytu", "laikyti", "laikyta", "laikaytame", "laikaytate"},
        {"To", "sing", "dainuoti", "Regular", "dainuotu", "dainuoti", "dainuota", "dainuotame", "laikatate"},
        {"To", "bring", "atnešti", "Regular", "atneštu", "atnešti", "atnešta", "atneštame", "atneštate"},
        {"To", "look", "žiūrėti", "Regular", "žiūrėtu", "žiūrėti", "žiūrėta", "žiūrėtame", "žiūrėtate"},
        {"To", "dance", "šokti", "Regular", "šoktu", "šokti", "šhokta", "šoktame", "šoktate"},
        {"To", "clean", "valyti", "Regular", "valytu", "valyti", "valyta", "valytame", "valytate"},
        {"To", "swim", "plaukti", "Regular", "plauktu", "plaukti", "plaukta", "plauktame", "plauktate"},
        {"To", "scream", "šaukti", "Regular", "šauktu", "šaukti", "šaukta", "šauktame", "šauktate"},
        {"To", "make", "daryti", "Regular", "darytu", "daryti", "daryta", "darytame", "darytate"},
        {"To", "repair", "taisyti", "Regular", "taisytu", "taisyti", "taisyta", "taisytame", "taisytate"},
        {"To", "love", "mylėti", "Regular", "mylėtu", "mylėti", "mylėta", "mylėtame", "mylėtate"},
        {"To", "read", "skaityti", "Regular", "skaitytu", "skaityti", "skaityta", "skaitytame", "skaitytate"},
        {"To", "write", "rašyti", "Regular", "rašytu", "rašyti", "rašyta", "rašytame", "rašytate"},
        {"To", "work", "dirbti", "Regular", "dirbtu", "dirbti", "dirbta", "dirbtame", "dirbtate"},
        {"To", "listen", "kalusyti", "Regular", "kalusytu", "kalusyti", "kalusyta", "kalusytame", "kalusytate"},
    };

    public static String lithuanianPro[] = {"Aš", "Tu", "Jis", "Jos", "Jie", "Jos", "Mes", "Jūs"};
    /*
     END LITHUANIAN DEPENDANCIES
     */
    
    /*
    BEGIN ESPERANTO DEPENDANCIES
    */
    
    /*
    Special ref:
    ĉ  ŝ  ĝ  ĥ  ĵ  ŭ
    */
    
    public static String esperantoList[][]={
        {"To","be","Esti","Regular","est"},
    };
    
    public static String esperantoPro[] = {"Mi","Vi","Li","Ŝi","Ĝi","Ni","Ili"};
    
    /*
    END ESPERANTO DEPENDANCIES
    */

}
